// Export Functionality Module

class ExportManager {
    static exportAnalysis() {
        if (!window.currentAnalysis) return;

        const languageSelect = document.getElementById('languageSelect');
        const content = `# Code Analysis Report
Generated: ${new Date().toLocaleString()}
Language: ${languageSelect.value.toUpperCase()}

## Code Explanation
${OutputFormatter.formatContent(window.currentAnalysis.explanation)}

## Issues Found
${OutputFormatter.formatContent(window.currentAnalysis.issues)}

## Suggestions
${OutputFormatter.formatContent(window.currentAnalysis.suggestions)}

## Tiger Style Recommendations
${OutputFormatter.formatContent(window.currentAnalysis.tigerStyle)}

---
Generated by Whitespace Code Analyzer
`;

        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `code-analysis-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    }
}

window.ExportManager = ExportManager;